SELECT 
    a.CODIGOASIGNATURA,
    a.NOMBREASI AS ASIGNATURA,
    p.NOMBREPRO AS PROFESOR,
    COUNT(ata.DNI) AS TOTAL_ALUMNOS_2025
FROM ASIGNATURA a
INNER JOIN PROFESOR p ON a.CODIGOPROFESOR = p.CODIGOPROFESOR
INNER JOIN ALUMNO_TIENE_ASIGNATURA ata ON a.CODIGOASIGNATURA = ata.CODIGOASIGNATURA
WHERE ata.ANO = 2025
GROUP BY a.CODIGOASIGNATURA, a.NOMBREASI, p.NOMBREPRO
ORDER BY TOTAL_ALUMNOS_2025 DESC;