--------------------------------------------------------
-- Archivo creado  - lunes-junio-15-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALUMNO
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."ALUMNO" 
   (	"DNI" VARCHAR2(9 BYTE), 
	"NOMBREALU" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALUMNO_TIENE_ASIGNATURA
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."ALUMNO_TIENE_ASIGNATURA" 
   (	"ANO" NUMBER(4,0), 
	"CODIGOASIGNATURA" NUMBER(9,0), 
	"DNI" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASIGNATURA
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."ASIGNATURA" 
   (	"CODIGOASIGNATURA" NUMBER(9,0), 
	"NOMBREASI" VARCHAR2(50 BYTE), 
	"CODIGOPROFESOR" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."DEPARTAMENTO" 
   (	"NOMBREDEP" VARCHAR2(50 BYTE), 
	"JEFE" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFESOR
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."PROFESOR" 
   (	"CODIGOPROFESOR" NUMBER(9,0), 
	"NOMBREPRO" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"NOMBREDEP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DEPARTAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_DEPARTAMENTO" ON "PROYECTO"."DEPARTAMENTO" ("NOMBREDEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ALUMNO_ASIGNATURA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_ALUMNO_ASIGNATURA" ON "PROYECTO"."ALUMNO_TIENE_ASIGNATURA" ("CODIGOASIGNATURA", "DNI", "ANO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ALUMNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_ALUMNO" ON "PROYECTO"."ALUMNO" ("DNI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROFESOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_PROFESOR" ON "PROYECTO"."PROFESOR" ("CODIGOPROFESOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ASIGNATURA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_ASIGNATURA" ON "PROYECTO"."ASIGNATURA" ("CODIGOASIGNATURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_CONTROL_ANIO_MATRICULA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO"."TRG_CONTROL_ANIO_MATRICULA" 
BEFORE INSERT ON ALUMNO_TIENE_ASIGNATURA
FOR EACH ROW
DECLARE
    v_anio_actual NUMBER(4);
BEGIN
    -- Extraemos el año actual del sistema
    v_anio_actual := TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'));

    -- Si intentan matricular en un año distinto, saltará el error
    IF :NEW.ANO <> v_anio_actual THEN
        RAISE_APPLICATION_ERROR(-20005, 'Error: No se permiten matrículas fuera del año académico en curso (' || v_anio_actual || ').');
    END IF;
END;

/
ALTER TRIGGER "PROYECTO"."TRG_CONTROL_ANIO_MATRICULA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_VERIFICAR_JEFE_DEP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO"."TRG_VERIFICAR_JEFE_DEP" 
BEFORE INSERT OR UPDATE ON DEPARTAMENTO
FOR EACH ROW
DECLARE
    v_dep_profesor VARCHAR2(50);
BEGIN
    IF :NEW.JEFE IS NOT NULL THEN
        SELECT NOMBREDEP INTO v_dep_profesor
        FROM PROFESOR
        WHERE CODIGOPROFESOR = :NEW.JEFE;

        IF v_dep_profesor <> :NEW.NOMBREDEP THEN
            RAISE_APPLICATION_ERROR(-20003, 'Error: El profesor asignado como jefe pertenece al departamento de ' || v_dep_profesor || ', no a ' || :NEW.NOMBREDEP);
        END IF;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20004, 'Error: El código de profesor introducido no existe.');
END;

/
ALTER TRIGGER "PROYECTO"."TRG_VERIFICAR_JEFE_DEP" ENABLE;
--------------------------------------------------------
--  DDL for Procedure MATRICULAR_ALUMNO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."MATRICULAR_ALUMNO" (
    P_DNI              IN VARCHAR2,
    P_CODIGOASIGNATURA IN NUMBER,
    P_ANO              IN NUMBER
) AS
BEGIN
    INSERT INTO ALUMNO_TIENE_ASIGNATURA (DNI, CODIGOASIGNATURA, ANO)
    VALUES (P_DNI, P_CODIGOASIGNATURA, P_ANO);

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Alumno matriculado correctamente.');
END;

/
--------------------------------------------------------
--  DDL for Function PROFESOR_DE_ALUMNO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PROYECTO"."PROFESOR_DE_ALUMNO" 
(
  DNI_ALUMNO IN ALUMNO.DNI%TYPE 
) RETURN PROFESOR.NOMBREPRO%TYPE AS
RESPUESTA PROFESOR.NOMBREPRO%TYPE;
BEGIN
    SELECT PR.NOMBREPRO
    INTO RESPUESTA
    FROM PROFESOR PR
    JOIN ASIGNATURA ASI ON PR.CODIGOPROFESOR = ASI.CODIGOPROFESOR
    JOIN alumno_tiene_asignatura ALT ON asi.codigoasignatura = alt.codigoasignatura
    JOIN ALUMNO AL ON alt.dni = al.dni
    WHERE al.dni = DNI_ALUMNO;
    RETURN RESPUESTA;
END;

/
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."DEPARTAMENTO" ADD CONSTRAINT "PK_DEPARTAMENTO" PRIMARY KEY ("NOMBREDEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFESOR
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."PROFESOR" MODIFY ("NOMBREPRO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."PROFESOR" MODIFY ("NOMBREDEP" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."PROFESOR" ADD CONSTRAINT "PK_PROFESOR" PRIMARY KEY ("CODIGOPROFESOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ALUMNO
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."ALUMNO" MODIFY ("NOMBREALU" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."ALUMNO" ADD CONSTRAINT "PK_ALUMNO" PRIMARY KEY ("DNI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASIGNATURA
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."ASIGNATURA" MODIFY ("NOMBREASI" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."ASIGNATURA" MODIFY ("CODIGOPROFESOR" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."ASIGNATURA" ADD CONSTRAINT "PK_ASIGNATURA" PRIMARY KEY ("CODIGOASIGNATURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ALUMNO_TIENE_ASIGNATURA
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."ALUMNO_TIENE_ASIGNATURA" ADD CONSTRAINT "PK_ALUMNO_ASIGNATURA" PRIMARY KEY ("CODIGOASIGNATURA", "DNI", "ANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ALUMNO_TIENE_ASIGNATURA
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."ALUMNO_TIENE_ASIGNATURA" ADD CONSTRAINT "FK_MATRICULA_ASIGNATURA" FOREIGN KEY ("CODIGOASIGNATURA")
	  REFERENCES "PROYECTO"."ASIGNATURA" ("CODIGOASIGNATURA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROYECTO"."ALUMNO_TIENE_ASIGNATURA" ADD CONSTRAINT "FK_MATRICULA_ALUMNO" FOREIGN KEY ("DNI")
	  REFERENCES "PROYECTO"."ALUMNO" ("DNI") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASIGNATURA
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."ASIGNATURA" ADD CONSTRAINT "FK_ASIGNATURA_PROFESOR" FOREIGN KEY ("CODIGOPROFESOR")
	  REFERENCES "PROYECTO"."PROFESOR" ("CODIGOPROFESOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."DEPARTAMENTO" ADD CONSTRAINT "FK_DEPARTAMENTO_JEFE" FOREIGN KEY ("JEFE")
	  REFERENCES "PROYECTO"."PROFESOR" ("CODIGOPROFESOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFESOR
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."PROFESOR" ADD CONSTRAINT "FK_PROFESOR_DEPARTAMENTO" FOREIGN KEY ("NOMBREDEP")
	  REFERENCES "PROYECTO"."DEPARTAMENTO" ("NOMBREDEP") ENABLE;
