--------------------------------------------------------
-- Archivo creado  - lunes-junio-15-2026   
--------------------------------------------------------
REM INSERTING into PROYECTO.ALUMNO
SET DEFINE OFF;
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('11111111A','Lucas Silva');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('22222222B','Mateo Fernández');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('33333333C','Martina Vega');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('44444444D','Daniela Cruz');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('55555555E','Nicolás Pastrana');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('66666666F','Sara Palacios');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('77777777G','Hugo San Miguel');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('88888888H','Sofía Lorente');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('99999999I','Bruno Delgado');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('12345678J','Paula Ortiz');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('87654321K','Álvaro Márquez');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('56781234L','Elena Prieto');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('43218765M','Diego Belmonte');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('98765432N','Irene Navarro');
Insert into PROYECTO.ALUMNO (DNI,NOMBREALU) values ('24681357P','Gabriel Soler');
REM INSERTING into PROYECTO.ALUMNO_TIENE_ASIGNATURA
SET DEFINE OFF;
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2025','5001','11111111A');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2025','5002','22222222B');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2025','5003','33333333C');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2025','5004','44444444D');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2025','5005','55555555E');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5006','66666666F');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5007','77777777G');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5008','88888888H');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5009','99999999I');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5010','12345678J');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5011','87654321K');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5012','56781234L');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5013','43218765M');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5014','98765432N');
Insert into PROYECTO.ALUMNO_TIENE_ASIGNATURA (ANO,CODIGOASIGNATURA,DNI) values ('2026','5015','24681357P');
REM INSERTING into PROYECTO.ASIGNATURA
SET DEFINE OFF;
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5001','Bases de Datos','1001');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5002','Álgebra Lineal','1002');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5003','Termodinámica','1003');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5004','Química Orgánica','1004');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5005','Genética Molecular','1005');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5006','Historia Contemporánea','1006');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5007','Ética y Moral','1007');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5008','Literatura Barroca','1008');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5009','Macroeconomía','1009');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5010','Derecho Constitucional','1010');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5011','Anatomía Humana','1011');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5012','Psicología Cognitiva','1012');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5013','Estructura Social','1013');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5014','Historia del Arte','1014');
Insert into PROYECTO.ASIGNATURA (CODIGOASIGNATURA,NOMBREASI,CODIGOPROFESOR) values ('5015','Mecánica de Fluidos','1015');
REM INSERTING into PROYECTO.DEPARTAMENTO
SET DEFINE OFF;
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Informática','1001');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Matemáticas','1002');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Física','1003');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Química','1004');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Biología','1005');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Historia','1006');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Filosofía','1007');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Lengua y Literatura','1008');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Economía','1009');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Derecho','1010');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Medicina','1011');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Psicología','1012');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Sociología','1013');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Arte y Diseño','1014');
Insert into PROYECTO.DEPARTAMENTO (NOMBREDEP,JEFE) values ('Ingeniería Civil','1015');
REM INSERTING into PROYECTO.PROFESOR
SET DEFINE OFF;
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1001','Carlos Mendoza','Calle Mayor 12','Informática');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1002','Ana Rodríguez','Av. Constitución 45','Matemáticas');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1003','Luis Martínez','Calle Pez 8','Física');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1004','Elena Gómez','Paseo del Prado 22','Química');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1005','David Alonso','Calle Luna 4','Biología');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1006','Sofía Ruiz','Av. Mediterráneo 89','Historia');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1007','Javier López','Calle Arenal 15','Filosofía');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1008','Carmen Torres','Calle Mayor 77','Lengua y Literatura');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1009','Alejandro Vidal','Av. Diagonal 320','Economía');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1010','Laura Sancho','Calle Serrano 14','Derecho');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1011','Pablo Iglesias','Gran Vía 54','Medicina');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1012','Cristina Peña','Calle Alcala 102','Psicología');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1013','Manuel Castro','Av. América 11','Sociología');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1014','Isabel Benítez','Calle Goya 9','Arte y Diseño');
Insert into PROYECTO.PROFESOR (CODIGOPROFESOR,NOMBREPRO,DIRECCION,NOMBREDEP) values ('1015','Jorge Herranz','Paseo Castellana 210','Ingeniería Civil');
